name: 'Branch Code Coverage'
on:
  push:
    branches: ['development', feature/*, hotfix/*, main, release/*]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: make build-local
      - name: Check test coverage
        run: npm run test:coverage
